;this file for FamiTone2 library generated by text2data tool

novapuzzle_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env9,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env11,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $04
	.word @env4,@env0,@env16
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env15
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env6,@env12,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env7,@env13,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env8,@env14,@env0
	.byte $00
	.byte $70 ;instrument $0a
	.word @env8,@env14,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$03,$c0,$00,$02
@env2:
	.byte $ca,$c6,$c3,$c1,$c1,$c0,$00,$05
@env3:
	.byte $cc,$c1,$c8,$c5,$c3,$c2,$c1,$03,$c0,$00,$08
@env4:
	.byte $cd,$cb,$c8,$c6,$c4,$c3,$c2,$c1,$c1,$00,$08
@env5:
	.byte $c1,$08,$c0,$00,$02
@env6:
	.byte $c3,$03,$c2,$05,$c1,$04,$c0,$00,$06
@env7:
	.byte $cc,$c7,$c4,$c3,$c2,$c1,$02,$c0,$00,$07
@env8:
	.byte $c6,$c3,$c1,$c0,$00,$03
@env9:
	.byte $c3,$c0,$00,$01
@env10:
	.byte $ba,$b9,$b6,$b9,$ba,$bb,$00,$05
@env11:
	.byte $c2,$bd,$00,$01
@env12:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env13:
	.byte $bf,$c0,$00,$01
@env14:
	.byte $be,$00,$00
@env15:
	.byte $b4,$a8,$00,$01
@env16:
	.byte $ba,$b4,$00,$01


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $87,$86,$41,$01,$3c,$00,$41,$01,$3c,$00,$47,$01,$41,$36,$00,$3d
	.byte $01,$41,$00,$81
@ref1:
	.byte $88,$44,$00,$86,$47,$3d,$33,$01,$44,$00,$46,$00,$4b,$01,$4a,$00
	.byte $40,$3c,$36,$00,$3d,$01,$41,$00,$81
@ref2:
	.byte $8a,$4b,$86,$4b,$46,$00,$41,$01,$40,$00,$55,$52,$83,$00,$36,$00
	.byte $3c,$00,$40,$00,$88,$45,$86,$40,$00,$3d,$40,$81
@ref3:
	.byte $00,$85,$47,$36,$00,$3d,$01,$3b,$00,$89,$4b,$3c,$00,$47,$01,$45
	.byte $00,$81
@ref4:
	.byte $87,$41,$01,$3c,$00,$41,$01,$3c,$00,$47,$01,$41,$36,$00,$3d,$01
	.byte $41,$00,$81
	.byte $ff,$17
	.word @ref1
@ref6:
	.byte $37,$01,$49,$01,$45,$41,$01,$40,$00,$47,$01,$44,$00,$41,$01,$40
	.byte $00,$88,$45,$86,$44,$00
@ref7:
	.byte $4f,$01,$4f,$01,$4b,$47,$01,$4f,$53,$01,$4b,$01,$47,$01,$45,$00
	.byte $81
@ref8:
	.byte $90,$55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$59,$55,$52,$81
@ref9:
	.byte $54,$85,$52,$85,$4e,$89,$53,$55,$52,$85,$4e,$91
@ref10:
	.byte $55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$4b,$59,$4a,$81
@ref11:
	.byte $54,$85,$58,$85,$5c,$8d,$5f,$5d,$59,$5c,$85,$55,$53,$54,$81
@ref12:
	.byte $55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$59,$55,$52,$81
	.byte $ff,$0c
	.word @ref9
	.byte $ff,$0f
	.word @ref10
	.byte $ff,$0f
	.word @ref11
@ref16:
	.byte $8e,$40,$89,$40,$91,$46,$89,$46,$91
@ref17:
	.byte $32,$89,$32,$91,$3c,$89,$3c,$89,$3e,$85
@ref18:
	.byte $40,$89,$40,$91,$46,$89,$46,$91
	.byte $ff,$0a
	.word @ref17
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref20:
	.byte $8e,$40,$89,$40,$89,$40,$85,$3c,$89,$3c,$85,$3d,$3c,$85
@ref21:
	.byte $46,$89,$46,$89,$46,$85,$4a,$89,$4a,$85,$4b,$4a,$85
@ref22:
	.byte $40,$89,$40,$89,$40,$85,$3c,$89,$3c,$85,$3d,$3c,$85
	.byte $ff,$0d
	.word @ref21
	.byte $ff,$0d
	.word @ref22
	.byte $ff,$0d
	.word @ref21
	.byte $ff,$0d
	.word @ref22
	.byte $ff,$0d
	.word @ref21
@ref28:
	.byte $3c,$89,$3d,$3c,$85,$3c,$85,$4a,$89,$4b,$4a,$85,$4a,$85
@ref29:
	.byte $40,$89,$41,$40,$85,$40,$85,$40,$89,$41,$3c,$85,$40,$85
	.byte $ff,$0e
	.word @ref28
@ref31:
	.byte $40,$89,$41,$40,$85,$40,$85,$46,$89,$47,$46,$85,$46,$85
	.byte $ff,$0e
	.word @ref28
	.byte $ff,$0e
	.word @ref29
	.byte $ff,$0e
	.word @ref28
	.byte $ff,$0e
	.word @ref31
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref40:
	.byte $80,$29,$8c,$29,$41,$80,$29,$8c,$33,$35,$80,$33,$8c,$35,$80,$29
	.byte $8c,$29,$41,$80,$29,$8c,$33,$35,$80,$33,$8c,$34,$81
@ref41:
	.byte $80,$2f,$8c,$2f,$47,$80,$2f,$8c,$3b,$3d,$80,$3b,$8c,$3d,$80,$33
	.byte $8c,$33,$4b,$80,$33,$8c,$4f,$4b,$80,$47,$8c,$40,$81
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
@ref48:
	.byte $25,$80,$25,$3d,$8c,$24,$85,$80,$25,$8c,$3d,$25,$33,$80,$33,$4b
	.byte $8c,$32,$85,$80,$32,$32,$8c,$4b,$32,$81
@ref49:
	.byte $29,$80,$29,$41,$8c,$28,$85,$80,$29,$8c,$41,$29,$29,$80,$29,$41
	.byte $8c,$28,$85,$80,$29,$8c,$41,$28,$81
	.byte $ff,$12
	.word @ref48
@ref51:
	.byte $29,$80,$29,$41,$8c,$28,$85,$80,$29,$8c,$41,$29,$2f,$80,$2f,$47
	.byte $8c,$2e,$85,$80,$2f,$46,$46,$8c,$2e,$81
	.byte $ff,$12
	.word @ref48
	.byte $ff,$11
	.word @ref49
	.byte $ff,$12
	.word @ref48
	.byte $ff,$12
	.word @ref51
@ref56:
	.byte $29,$80,$29,$8c,$41,$28,$85,$80,$29,$8c,$41,$29,$2f,$80,$2f,$47
	.byte $8c,$2e,$85,$80,$2f,$8c,$47,$2e,$81
@ref57:
	.byte $33,$80,$33,$8c,$4b,$32,$85,$80,$33,$8c,$4b,$33,$25,$80,$25,$8c
	.byte $3d,$80,$25,$24,$24,$8c,$3d,$80,$27,$8c,$3e,$81
	.byte $ff,$11
	.word @ref56
	.byte $ff,$12
	.word @ref57
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref60:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$21,$82
	.byte $21,$21,$84,$21,$82,$21,$92,$21,$82,$21,$84,$21,$92,$20,$81
@ref61:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$21,$82
	.byte $21,$21,$84,$21,$82,$21,$92,$20,$20,$82,$21,$84,$21,$92,$20,$81
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
@ref67:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$20,$20
	.byte $82,$21,$21,$84,$21,$82,$21,$84,$20,$85,$20,$85
@ref68:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$82,$21,$84,$21,$82,$21,$21,$21,$84,$21,$94,$20,$81
@ref69:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$84,$21,$82,$21,$21,$84,$21,$82,$21,$84,$21,$94,$20,$81
	.byte $ff,$11
	.word @ref68
@ref71:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$84,$21,$82,$21,$21,$84,$21,$82,$21,$84,$21,$20,$81
	.byte $ff,$11
	.word @ref68
	.byte $ff,$11
	.word @ref69
	.byte $ff,$11
	.word @ref68
	.byte $ff,$11
	.word @ref71
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
	.byte $ff,$11
	.word @ref67
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
