;this file for FamiTone2 library generated by text2data tool

novapuzzle_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env10,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env12,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env11,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $04
	.word @env4,@env0,@env18
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env17
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env10,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env6,@env13,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env7,@env14,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env8,@env16,@env0
	.byte $00
	.byte $70 ;instrument $0a
	.word @env8,@env16,@env0
	.byte $00
	.byte $70 ;instrument $0b
	.word @env9,@env14,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env6,@env15,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$03,$c0,$00,$02
@env2:
	.byte $ca,$c6,$c3,$c1,$c1,$c0,$00,$05
@env3:
	.byte $cc,$c1,$c8,$c5,$c3,$c2,$c1,$03,$c0,$00,$08
@env4:
	.byte $cd,$cb,$c8,$c6,$c4,$c3,$c2,$c1,$c1,$00,$08
@env5:
	.byte $c1,$08,$c0,$00,$02
@env6:
	.byte $c5,$c4,$c3,$c3,$c2,$05,$c1,$04,$c0,$00,$08
@env7:
	.byte $cc,$c7,$c4,$c3,$c2,$c1,$02,$c0,$00,$07
@env8:
	.byte $c6,$c3,$c1,$c0,$00,$03
@env9:
	.byte $c7,$c9,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$03,$c1,$00,$0a
@env10:
	.byte $c3,$c0,$00,$01
@env11:
	.byte $ba,$b9,$b6,$b9,$ba,$bb,$00,$05
@env12:
	.byte $c2,$bd,$00,$01
@env13:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env14:
	.byte $bf,$c0,$00,$01
@env15:
	.byte $c0,$c0,$c3,$c3,$c8,$c8,$00,$00
@env16:
	.byte $be,$00,$00
@env17:
	.byte $b4,$a8,$00,$01
@env18:
	.byte $ba,$b4,$00,$01


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $87,$86,$41,$01,$3c,$00,$41,$01,$3c,$00,$47,$01,$41,$36,$00,$3d
	.byte $01,$41,$00,$81
@ref1:
	.byte $88,$44,$00,$86,$47,$3d,$33,$01,$44,$00,$46,$00,$4b,$01,$4a,$00
	.byte $40,$3c,$36,$00,$3d,$01,$41,$00,$81
@ref2:
	.byte $8a,$4b,$86,$4b,$46,$00,$41,$01,$40,$00,$55,$52,$83,$00,$36,$00
	.byte $3c,$00,$40,$00,$88,$45,$86,$40,$00,$3d,$40,$81
@ref3:
	.byte $00,$85,$47,$36,$00,$3d,$01,$3b,$00,$89,$4b,$3c,$00,$47,$01,$45
	.byte $00,$81
@ref4:
	.byte $87,$41,$01,$3c,$00,$41,$01,$3c,$00,$47,$01,$41,$36,$00,$3d,$01
	.byte $41,$00,$81
	.byte $ff,$17
	.word @ref1
@ref6:
	.byte $37,$01,$49,$01,$45,$41,$01,$40,$00,$47,$01,$44,$00,$41,$01,$40
	.byte $00,$88,$45,$86,$44,$00
@ref7:
	.byte $4f,$01,$4f,$01,$4b,$47,$01,$4f,$53,$01,$4b,$01,$47,$01,$45,$00
	.byte $81
@ref8:
	.byte $90,$55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$59,$55,$52,$81
@ref9:
	.byte $54,$85,$52,$85,$4e,$89,$53,$55,$52,$85,$4e,$91
@ref10:
	.byte $55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$4b,$59,$4a,$81
@ref11:
	.byte $54,$85,$58,$85,$5c,$8d,$5f,$5d,$59,$5c,$85,$55,$53,$54,$81
@ref12:
	.byte $55,$4a,$85,$3c,$8d,$55,$59,$52,$85,$4a,$85,$59,$55,$52,$81
	.byte $ff,$0c
	.word @ref9
	.byte $ff,$0f
	.word @ref10
	.byte $ff,$0f
	.word @ref11
@ref16:
	.byte $8e,$40,$89,$40,$91,$46,$89,$46,$91
@ref17:
	.byte $32,$89,$32,$91,$3c,$89,$3c,$89,$3e,$85
@ref18:
	.byte $40,$89,$40,$91,$46,$89,$46,$91
	.byte $ff,$0a
	.word @ref17
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref20:
	.byte $8e,$40,$89,$40,$89,$40,$85,$3c,$89,$3c,$85,$3d,$3c,$85
@ref21:
	.byte $46,$89,$46,$89,$46,$85,$4a,$89,$4a,$85,$4b,$4a,$85
@ref22:
	.byte $40,$89,$40,$89,$40,$85,$3c,$89,$3c,$85,$3d,$3c,$85
	.byte $ff,$0d
	.word @ref21
	.byte $ff,$0d
	.word @ref22
	.byte $ff,$0d
	.word @ref21
	.byte $ff,$0d
	.word @ref22
	.byte $ff,$0d
	.word @ref21
@ref28:
	.byte $3c,$89,$3d,$3c,$85,$3c,$85,$4a,$89,$4b,$4a,$85,$4a,$85
@ref29:
	.byte $40,$89,$41,$40,$85,$40,$85,$40,$89,$41,$3c,$85,$40,$85
	.byte $ff,$0e
	.word @ref28
@ref31:
	.byte $40,$89,$41,$40,$85,$40,$85,$46,$89,$47,$46,$85,$46,$85
	.byte $ff,$0e
	.word @ref28
	.byte $ff,$0e
	.word @ref29
	.byte $ff,$0e
	.word @ref28
	.byte $ff,$0e
	.word @ref31
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref40:
	.byte $80,$29,$8c,$29,$41,$80,$29,$8c,$33,$35,$80,$33,$8c,$35,$80,$29
	.byte $8c,$29,$41,$80,$29,$8c,$33,$35,$80,$33,$8c,$34,$81
@ref41:
	.byte $80,$2f,$8c,$2f,$47,$80,$2f,$8c,$3b,$3d,$80,$3b,$8c,$3d,$80,$33
	.byte $8c,$33,$4b,$80,$33,$8c,$4f,$4b,$80,$47,$8c,$40,$81
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref40
	.byte $ff,$11
	.word @ref41
@ref48:
	.byte $25,$80,$25,$3d,$8c,$24,$85,$80,$25,$8c,$3d,$25,$33,$80,$33,$4b
	.byte $8c,$32,$85,$80,$32,$32,$8c,$4b,$32,$81
@ref49:
	.byte $29,$80,$29,$41,$8c,$28,$85,$80,$29,$8c,$41,$29,$29,$80,$29,$41
	.byte $8c,$28,$85,$80,$29,$8c,$41,$28,$81
	.byte $ff,$12
	.word @ref48
@ref51:
	.byte $29,$80,$29,$41,$8c,$28,$85,$80,$29,$8c,$41,$29,$2f,$80,$2f,$47
	.byte $8c,$2e,$85,$80,$2f,$46,$46,$8c,$2e,$81
	.byte $ff,$12
	.word @ref48
	.byte $ff,$11
	.word @ref49
	.byte $ff,$12
	.word @ref48
	.byte $ff,$12
	.word @ref51
@ref56:
	.byte $29,$80,$29,$8c,$41,$28,$85,$80,$29,$8c,$41,$29,$2f,$80,$2f,$47
	.byte $8c,$2e,$85,$80,$2f,$8c,$47,$2e,$81
@ref57:
	.byte $33,$80,$33,$8c,$4b,$32,$85,$80,$33,$8c,$4b,$33,$25,$80,$25,$8c
	.byte $3d,$80,$25,$24,$24,$8c,$3d,$80,$27,$8c,$3e,$81
	.byte $ff,$11
	.word @ref56
	.byte $ff,$12
	.word @ref57
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref60:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$21,$82
	.byte $21,$21,$84,$21,$82,$21,$92,$21,$82,$21,$84,$21,$92,$20,$81
@ref61:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$21,$82
	.byte $21,$21,$84,$21,$82,$21,$92,$20,$20,$82,$21,$84,$21,$92,$20,$81
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
@ref67:
	.byte $82,$21,$92,$21,$84,$21,$92,$21,$82,$21,$21,$84,$21,$92,$20,$20
	.byte $82,$21,$21,$84,$21,$82,$21,$84,$20,$85,$20,$85
@ref68:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$82,$21,$84,$21,$82,$21,$21,$21,$84,$21,$94,$20,$81
@ref69:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$84,$21,$82,$21,$21,$84,$21,$82,$21,$84,$21,$94,$20,$81
	.byte $ff,$11
	.word @ref68
@ref71:
	.byte $82,$21,$94,$21,$84,$21,$82,$21,$94,$21,$82,$21,$84,$21,$94,$20
	.byte $85,$84,$21,$82,$21,$21,$84,$21,$82,$21,$84,$21,$20,$81
	.byte $ff,$11
	.word @ref68
	.byte $ff,$11
	.word @ref69
	.byte $ff,$11
	.word @ref68
	.byte $ff,$11
	.word @ref71
	.byte $ff,$11
	.word @ref60
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref60
	.byte $ff,$11
	.word @ref67
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref100:
	.byte $83,$8e,$32,$89,$36,$91,$28,$89,$2c,$8d
@ref101:
	.byte $83,$32,$89,$36,$91,$28,$89,$2c,$8d
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref101
@ref104:
	.byte $96,$53,$54,$00,$3c,$00,$59,$01,$4f,$00,$85,$4f,$52,$00,$54,$00
	.byte $59,$01,$4b,$00,$85
@ref105:
	.byte $55,$58,$00,$4e,$00,$45,$01,$55,$00,$85,$4f,$52,$00,$54,$00,$59
	.byte $01,$4b,$00,$85
@ref106:
	.byte $53,$54,$00,$3c,$00,$59,$01,$4f,$00,$85,$4f,$52,$00,$54,$00,$59
	.byte $01,$4b,$00,$85
	.byte $ff,$14
	.word @ref105
@ref108:
	.byte $86,$3c,$85,$88,$43,$86,$4a,$85,$46,$85,$3d,$88,$45,$86,$45,$3d
	.byte $38,$85,$3c,$85,$00,$81
@ref109:
	.byte $4b,$41,$45,$46,$89,$00,$85,$47,$3d,$41,$44,$89,$00,$85
@ref110:
	.byte $3c,$85,$88,$43,$86,$4a,$85,$46,$85,$3d,$88,$45,$86,$45,$3d,$38
	.byte $85,$3c,$85,$00,$81
@ref111:
	.byte $88,$53,$86,$51,$4b,$46,$85,$4a,$85,$38,$3c,$43,$47,$4b,$47,$01
	.byte $42,$85,$00,$81
	.byte $ff,$09
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref101
@ref116:
	.byte $86,$29,$28,$00,$24,$00,$1f,$29,$1e,$00,$24,$00,$29,$2f,$2e,$00
	.byte $28,$00,$24,$85,$1e,$00,$25,$28,$00
@ref117:
	.byte $29,$36,$00,$32,$00,$29,$01,$28,$00,$2e,$00,$33,$3d,$01,$36,$00
	.byte $33,$01,$36,$85,$00,$81
@ref118:
	.byte $41,$40,$00,$3c,$00,$37,$29,$36,$00,$3c,$00,$41,$88,$45,$86,$4a
	.byte $00,$44,$00,$47,$01,$40,$00,$3d,$40,$00
@ref119:
	.byte $3d,$40,$00,$3d,$33,$36,$00,$3d,$37,$32,$00,$28,$00,$28,$00,$25
	.byte $28,$85,$00,$89
	.byte $ff,$11
	.word @ref110
	.byte $ff,$0e
	.word @ref109
	.byte $ff,$11
	.word @ref110
	.byte $ff,$12
	.word @ref111
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref124:
	.byte $bf
@ref125:
	.byte $bf
@ref126:
	.byte $bf
@ref127:
	.byte $bf
	.byte $ff,$09
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref101
@ref132:
	.byte $3c,$85,$3c,$85,$38,$85,$38,$85,$98,$3f,$3e,$85,$8e,$3c,$89,$3c
	.byte $85
	.byte $ff,$0f
	.word @ref132
	.byte $ff,$0f
	.word @ref132
	.byte $ff,$0f
	.word @ref132
@ref136:
	.byte $bf
@ref137:
	.byte $bf
@ref138:
	.byte $bf
@ref139:
	.byte $bf
@ref140:
	.byte $40,$8d,$98,$3a,$8d,$8e,$3c,$8d,$98,$40,$8d
@ref141:
	.byte $8e,$40,$8d,$98,$3a,$8d,$8e,$3c,$8d,$98,$40,$8d
	.byte $ff,$08
	.word @ref141
	.byte $ff,$08
	.word @ref141
@ref144:
	.byte $8e,$3c,$85,$3c,$85,$38,$85,$38,$85,$98,$3f,$3e,$85,$8e,$3c,$89
	.byte $3c,$85
	.byte $ff,$0f
	.word @ref132
	.byte $ff,$0f
	.word @ref132
	.byte $ff,$0f
	.word @ref132
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref148:
	.byte $8c,$24,$85,$32,$85,$28,$85,$32,$85,$1e,$85,$32,$85,$2d,$32,$85
	.byte $3c,$81
@ref149:
	.byte $24,$85,$32,$85,$28,$85,$32,$85,$1e,$85,$32,$85,$2d,$32,$85,$22
	.byte $81
@ref150:
	.byte $24,$85,$32,$85,$28,$85,$32,$85,$1e,$85,$32,$85,$2d,$32,$85,$3c
	.byte $81
	.byte $ff,$11
	.word @ref149
	.byte $ff,$11
	.word @ref150
	.byte $ff,$11
	.word @ref149
	.byte $ff,$11
	.word @ref150
	.byte $ff,$11
	.word @ref149
@ref156:
	.byte $3d,$25,$3c,$85,$38,$85,$38,$85,$37,$1f,$37,$32,$85,$33,$32,$85
	.byte $ff,$10
	.word @ref156
	.byte $ff,$10
	.word @ref156
	.byte $ff,$10
	.word @ref156
	.byte $ff,$11
	.word @ref150
	.byte $ff,$11
	.word @ref149
	.byte $ff,$11
	.word @ref150
	.byte $ff,$11
	.word @ref149
@ref164:
	.byte $28,$85,$3c,$85,$36,$85,$32,$85,$25,$25,$3b,$3c,$85,$3b,$3c,$85
	.byte $ff,$10
	.word @ref164
	.byte $ff,$10
	.word @ref164
	.byte $ff,$10
	.word @ref164
	.byte $ff,$10
	.word @ref156
	.byte $ff,$10
	.word @ref156
	.byte $ff,$10
	.word @ref156
	.byte $ff,$10
	.word @ref156
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref172:
	.byte $82,$21,$92,$20,$20,$84,$21,$92,$21,$82,$21,$92,$21,$84,$21,$94
	.byte $21,$82,$21,$92,$20,$20,$84,$21,$92,$21,$82,$21,$92,$21,$84,$21
	.byte $94,$20,$81
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
@ref179:
	.byte $82,$21,$92,$20,$20,$84,$21,$92,$21,$82,$21,$92,$21,$84,$21,$94
	.byte $21,$82,$21,$92,$20,$20,$84,$21,$92,$21,$82,$21,$21,$94,$21,$84
	.byte $20,$81
@ref180:
	.byte $82,$21,$21,$84,$21,$92,$21,$82,$21,$94,$21,$84,$21,$92,$21,$82
	.byte $21,$21,$84,$21,$92,$21,$82,$21,$94,$21,$84,$21,$92,$20,$81
	.byte $ff,$11
	.word @ref180
	.byte $ff,$11
	.word @ref180
	.byte $ff,$11
	.word @ref180
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref179
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$13
	.word @ref172
	.byte $ff,$11
	.word @ref180
	.byte $ff,$11
	.word @ref180
	.byte $ff,$11
	.word @ref180
	.byte $ff,$11
	.word @ref180
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
@ref205:
	.byte $bf
@ref206:
	.byte $bf
@ref207:
	.byte $bf
@ref208:
	.byte $bf
@ref209:
	.byte $bf
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@ref212:
	.byte $bf
@ref213:
	.byte $bf
@ref214:
	.byte $bf
@ref215:
	.byte $bf
@ref216:
	.byte $bf
@ref217:
	.byte $bf
@ref218:
	.byte $bf
@ref219:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
