;this file for FamiTone2 library generated by text2data tool

Original_music_data:
	.byte 16
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,348,290
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,450,375
	.word @song13ch0,@song13ch1,@song13ch2,@song13ch3,@song13ch4,307,256
	.word @song14ch0,@song14ch1,@song14ch2,@song14ch3,@song14ch4,307,256
	.word @song15ch0,@song15ch1,@song15ch2,@song15ch3,@song15ch4,307,256

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env14,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env4,@env16,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env17,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env8,@env19,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env9,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $09
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env11,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env12,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env3,@env15,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env13,@env18,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$cb,$02,$cc,$c9,$c5,$c3,$c0,$00,$07
@env2:
	.byte $c6,$cb,$cc,$cb,$c7,$c5,$c2,$00,$06
@env3:
	.byte $ce,$cf,$02,$ce,$cd,$cc,$cb,$c9,$c8,$c6,$c4,$c0,$00,$0b
@env4:
	.byte $cf,$03,$ce,$02,$cd,$02,$cc,$03,$cb,$02,$ca,$02,$c9,$02,$c8,$03
	.byte $c7,$02,$c6,$02,$c5,$02,$c4,$03,$c3,$02,$c2,$02,$c1,$02,$c0,$00
	.byte $1e
@env5:
	.byte $ce,$cd,$cc,$cb,$c9,$c8,$c5,$c3,$c1,$c0,$00,$09
@env6:
	.byte $c7,$cb,$cf,$02,$cd,$cb,$ca,$c8,$c6,$c4,$c1,$c0,$00,$0b
@env7:
	.byte $c7,$cc,$cf,$cc,$ca,$c8,$c5,$c3,$c1,$c0,$00,$09
@env8:
	.byte $cf,$ce,$cc,$ca,$c9,$c7,$c5,$c4,$c2,$c0,$00,$09
@env9:
	.byte $c8,$c4,$c0,$c1,$c0,$00,$04
@env10:
	.byte $c8,$c8,$c7,$02,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$c2,$c1,$c0
	.byte $00,$0f
@env11:
	.byte $c2,$02,$c3,$c3,$c4,$c4,$00,$05
@env12:
	.byte $cf,$ce,$cd,$cc,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$c6
	.byte $c5,$03,$c4,$03,$c3,$04,$c2,$07,$c1,$0a,$c0,$00,$1a
@env13:
	.byte $ce,$ce,$cf,$cd,$cb,$c3,$00,$05
@env14:
	.byte $bf,$bc,$ba,$ba,$bc,$bf,$00,$05
@env15:
	.byte $c0,$c0,$c1,$c2,$c4,$c4,$c6,$00,$06
@env16:
	.byte $b7,$ba,$be,$c0,$05,$c0,$00,$05
@env17:
	.byte $bf,$bd,$bb,$bb,$bc,$bc,$c0,$00,$06
@env18:
	.byte $c0,$c3,$c2,$c0,$bb,$b6,$b6,$00,$06
@env19:
	.byte $c0,$b6,$00,$01


@song0ch0:
	.byte $fb,$07
@ref0:
	.byte $80,$50,$83,$42,$83,$46,$48,$4c,$83,$42,$83,$3f,$42,$83,$47,$46
	.byte $4d,$50,$85,$42,$85
@ref1:
	.byte $50,$83,$42,$83,$46,$48,$4c,$83,$42,$83,$3f,$42,$83,$47,$46,$4d
	.byte $3e,$85,$42,$85
@ref2:
	.byte $49,$50,$43,$44,$46,$48,$4d,$48,$43,$42,$4d,$43,$3e,$43,$3e,$47
	.byte $4d,$43,$42,$46,$4c,$81
@ref3:
	.byte $49,$50,$42,$42,$44,$46,$48,$4d,$48,$43,$42,$43,$43,$3e,$43,$3e
	.byte $4d,$51,$43,$42,$46,$4c,$81
@song0ch0loop:
	.byte $ff,$14
	.word @ref0
	.byte $ff,$14
	.word @ref1
	.byte $ff,$16
	.word @ref2
	.byte $ff,$17
	.word @ref3
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref8:
	.byte $bf
@ref9:
	.byte $bf
@ref10:
	.byte $bf
@ref11:
	.byte $bf
@song0ch1loop:
@ref12:
	.byte $85,$80,$38,$83,$3f,$42,$83,$4c,$87,$38,$83,$3e,$87,$46,$85,$4c
	.byte $85
@ref13:
	.byte $85,$38,$83,$3f,$42,$83,$4c,$87,$38,$83,$3e,$87,$46,$85,$4c,$85
@ref14:
	.byte $bf
@ref15:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref16:
	.byte $00,$bd
@ref17:
	.byte $00,$bd
@ref18:
	.byte $00,$bd
@ref19:
	.byte $00,$bd
@song0ch2loop:
@ref20:
	.byte $00,$bd
@ref21:
	.byte $00,$bd
@ref22:
	.byte $00,$bd
@ref23:
	.byte $00,$bd
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref24:
	.byte $82,$0a,$0a,$0b,$13,$0a,$0a,$0b,$13,$13,$0b,$0a,$0a,$0b,$13,$0a
	.byte $0a,$0b,$13,$13,$0a,$81
@ref25:
	.byte $0a,$0a,$0b,$13,$0a,$0a,$0b,$13,$13,$0b,$0a,$0a,$0b,$13,$0a,$0a
	.byte $0b,$13,$13,$0a,$81
	.byte $ff,$15
	.word @ref25
	.byte $ff,$15
	.word @ref25
@song0ch3loop:
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref25
	.byte $ff,$15
	.word @ref25
@ref31:
	.byte $00,$bd
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@song0ch4loop:
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref40:
	.byte $80,$47,$50,$4d,$4b,$42,$46,$85,$38,$3e,$43,$47,$50,$4d,$4b,$42
	.byte $46,$85,$38,$3e,$42,$81
@ref41:
	.byte $2a,$20,$1c,$2a,$2e,$83,$1c,$20,$26,$2a,$2e,$34,$85,$2a,$2e,$34
	.byte $38,$3e,$42,$46,$4c,$50,$46,$3e,$38,$87
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $47,$50,$4d,$4b,$42,$46,$85,$38,$3e,$43,$47,$50,$4d,$4b,$42,$46
	.byte $85,$38,$3e,$42,$81
	.byte $ff,$1a
	.word @ref41
@ref46:
	.byte $40,$40,$40,$52,$5c,$85,$40,$85,$4e,$85,$4a,$4a,$4a,$58,$5c,$85
	.byte $52,$85,$58,$85
	.byte $ff,$14
	.word @ref46
	.byte $ff,$14
	.word @ref46
	.byte $ff,$14
	.word @ref46
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref50:
	.byte $00,$bd
@ref51:
	.byte $bf
@ref52:
	.byte $80,$42,$83,$46,$39,$42,$38,$43,$46,$4c,$83,$35,$42,$83,$46,$39
	.byte $42,$38,$43,$46,$4c,$83,$34,$81
@ref53:
	.byte $3e,$83,$46,$39,$42,$38,$43,$46,$4c,$83,$39,$3e,$83,$46,$39,$42
	.byte $38,$43,$46,$4c,$83,$38,$81
@ref54:
	.byte $42,$83,$46,$39,$42,$38,$43,$46,$4c,$83,$35,$42,$83,$46,$39,$42
	.byte $38,$43,$46,$4c,$83,$34,$81
@ref55:
	.byte $42,$38,$34,$42,$46,$83,$34,$38,$3e,$42,$46,$4c,$85,$42,$46,$4c
	.byte $50,$56,$5a,$5e,$4c,$50,$46,$3e,$38,$87
@ref56:
	.byte $86,$33,$84,$4b,$32,$83,$32,$4a,$85,$54,$85,$86,$36,$85,$84,$5c
	.byte $85,$58,$8d
@ref57:
	.byte $86,$3a,$8d,$84,$63,$61,$5d,$59,$86,$3c,$8d,$84,$52,$8d
@ref58:
	.byte $40,$8d,$44,$85,$48,$4a,$4f,$54,$8d,$52,$8d
@ref59:
	.byte $4e,$8d,$5c,$54,$52,$4e,$87,$4a,$85,$4e,$85,$4e,$4a,$4e,$4a,$4e
	.byte $85
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref60:
	.byte $80,$50,$56,$5a,$5f,$65,$68,$83,$56,$5f,$5e,$65,$50,$56,$5a,$5f
	.byte $65,$68,$83,$56,$5f,$5e,$64,$81
@ref61:
	.byte $38,$3e,$42,$46,$4c,$50,$56,$5a,$5e,$64,$68,$a9
@ref62:
	.byte $50,$56,$5a,$5f,$65,$68,$83,$56,$5f,$5e,$65,$50,$56,$5a,$5f,$65
	.byte $68,$83,$56,$5f,$5e,$64,$81
	.byte $ff,$0c
	.word @ref61
	.byte $ff,$17
	.word @ref62
	.byte $ff,$0c
	.word @ref61
@ref66:
	.byte $4a,$4b,$58,$5d,$61,$4e,$52,$5c,$4e,$5d,$5f,$65,$5e,$57,$65,$5c
	.byte $5f,$54,$5d,$52,$54,$81
@ref67:
	.byte $bf
	.byte $ff,$16
	.word @ref66
@ref69:
	.byte $bf
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref70:
	.byte $82,$0f,$0f,$14,$83,$0e,$0e,$0f,$0e,$15,$0f,$0f,$0f,$14,$83,$0e
	.byte $0e,$0f,$0e,$15,$0e,$81
@ref71:
	.byte $0f,$0f,$14,$83,$0e,$0e,$0f,$0e,$15,$0f,$0f,$0f,$14,$83,$0e,$0e
	.byte $0f,$0e,$15,$0e,$81
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $ff,$15
	.word @ref71
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$04
@song2ch0loop:
@ref90:
	.byte $86,$4f,$55,$00,$85,$4f,$55,$00,$85,$55,$59,$01,$55,$59,$01,$4a
	.byte $85
@ref91:
	.byte $4f,$51,$5d,$58,$89,$52,$85,$4e,$85,$4b,$4e,$89,$4a,$85
@ref92:
	.byte $4f,$55,$00,$85,$4f,$55,$00,$85,$55,$59,$01,$55,$59,$01,$4a,$85
	.byte $ff,$0e
	.word @ref91
	.byte $ff,$10
	.word @ref92
	.byte $ff,$0e
	.word @ref91
@ref96:
	.byte $4b,$54,$85,$4b,$52,$85,$4b,$4e,$a1
@ref97:
	.byte $4b,$54,$85,$4b,$54,$85,$4b,$4e,$a1
@ref98:
	.byte $00,$85,$54,$85,$00,$85,$4e,$85,$00,$85,$58,$85,$00,$85,$4e,$85
	.byte $ff,$10
	.word @ref98
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@ref102:
	.byte $84,$1e,$89,$1f,$24,$85,$25,$28,$89,$2d,$37,$2c,$85,$24,$85
@ref103:
	.byte $1f,$28,$85,$1b,$22,$85,$1b,$1e,$a1
@ref104:
	.byte $1e,$89,$1f,$24,$85,$25,$28,$89,$2d,$37,$2c,$85,$24,$85
@ref105:
	.byte $1f,$28,$85,$1b,$22,$85,$1b,$24,$a1
	.byte $ff,$0e
	.word @ref104
	.byte $ff,$09
	.word @ref105
@ref108:
	.byte $1a,$85,$32,$85,$1b,$1b,$32,$85,$1a,$85,$33,$1b,$1b,$1f,$23,$24
	.byte $81
@ref109:
	.byte $1e,$85,$1a,$85,$24,$85,$1f,$1a,$85,$1f,$1b,$1b,$29,$24,$89
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
@ref114:
	.byte $bf
@ref115:
	.byte $bf
@ref116:
	.byte $bf
@ref117:
	.byte $bf
@ref118:
	.byte $bf
@ref119:
	.byte $bf
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref120:
	.byte $82,$21,$21,$0e,$85,$10,$85,$14,$0a,$83,$0a,$0a,$83,$20,$85,$10
	.byte $85,$06,$85
@ref121:
	.byte $21,$21,$0e,$85,$10,$85,$14,$0a,$83,$0a,$0a,$83,$20,$85,$10,$85
	.byte $06,$85
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $ff,$12
	.word @ref121
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref130:
	.byte $bf
@ref131:
	.byte $bf
@ref132:
	.byte $bf
@ref133:
	.byte $bf
@ref134:
	.byte $bf
@ref135:
	.byte $bf
@ref136:
	.byte $bf
@ref137:
	.byte $bf
@ref138:
	.byte $bf
@ref139:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref140:
	.byte $84,$1a,$00,$1a,$1a,$1f,$1e,$25,$28,$22,$1e,$25,$1f,$80,$32,$00
	.byte $32,$32,$37,$36,$3d,$40,$3a,$36,$3d,$36,$81
@ref141:
	.byte $84,$1a,$00,$1a,$1a,$1f,$1e,$25,$28,$22,$1e,$25,$80,$1f,$41,$40
	.byte $3d,$40,$3c,$3c,$3a,$3a,$36,$36,$32,$85
	.byte $ff,$19
	.word @ref140
	.byte $ff,$18
	.word @ref141
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref144:
	.byte $bf
@ref145:
	.byte $bf
@ref146:
	.byte $80,$4a,$54,$4a,$54,$58,$58,$58,$58,$4a,$8d,$4a,$54,$4a,$54,$54
	.byte $54,$54,$54,$58,$8d
@ref147:
	.byte $4a,$54,$4a,$54,$58,$58,$58,$58,$4a,$8d,$4a,$54,$4a,$54,$54,$54
	.byte $54,$54,$58,$8d
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref148:
	.byte $bf
@ref149:
	.byte $bf
@ref150:
	.byte $bf
@ref151:
	.byte $bf
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref152:
	.byte $88,$0e,$16,$0f,$17,$0e,$17,$0e,$0e,$0e,$16,$0e,$0e,$0e,$12,$12
	.byte $0b,$13,$0a,$13,$0a,$0a,$0a,$12,$0a,$0a,$0a
@ref153:
	.byte $0e,$16,$0f,$17,$0e,$17,$0e,$0e,$0e,$16,$0e,$0e,$0e,$12,$12,$0b
	.byte $13,$0a,$13,$0a,$0a,$0a,$12,$0a,$0a,$0a
	.byte $ff,$1a
	.word @ref153
	.byte $ff,$1a
	.word @ref153
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref156:
	.byte $bf
@ref157:
	.byte $bf
@ref158:
	.byte $bf
@ref159:
	.byte $bf
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref160:
	.byte $bf
@ref161:
	.byte $bf
@ref162:
	.byte $bf
@ref163:
	.byte $bf
@ref164:
	.byte $80,$33,$33,$4b,$32,$4a,$32,$4a,$33,$4b,$33,$33,$33,$4b,$32,$4a
	.byte $32,$4a,$33,$4b,$32,$81
@ref165:
	.byte $33,$33,$4b,$32,$4a,$32,$4a,$33,$4b,$33,$33,$33,$4b,$32,$4a,$32
	.byte $4a,$33,$4b,$32,$81
	.byte $ff,$15
	.word @ref165
	.byte $ff,$15
	.word @ref165
	.byte $ff,$15
	.word @ref165
	.byte $ff,$15
	.word @ref165
@ref170:
	.byte $bf
@ref171:
	.byte $bf
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref172:
	.byte $bf
@ref173:
	.byte $bf
@ref174:
	.byte $86,$32,$87,$00,$3a,$87,$00,$3c,$87,$00,$3b,$37,$33,$37,$3b,$37
	.byte $32,$00
@ref175:
	.byte $32,$87,$00,$2c,$87,$00,$36,$87,$00,$3b,$37,$33,$37,$3b,$37,$32
	.byte $00
@ref176:
	.byte $32,$87,$00,$3a,$87,$00,$3c,$87,$00,$3b,$37,$33,$37,$3b,$37,$32
	.byte $00
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
@ref182:
	.byte $32,$87,$00,$3a,$87,$00,$3c,$8d,$3b,$37,$32,$85,$32,$85
@ref183:
	.byte $32,$87,$00,$2c,$87,$00,$36,$8d,$32,$85,$36,$85,$32,$85
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
	.byte $ff,$11
	.word @ref174
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref175
@ref194:
	.byte $bf
@ref195:
	.byte $bf
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $88,$20,$20,$21,$0d,$21,$21,$21,$0d,$21,$20,$20,$21,$0d,$21,$21
	.byte $21,$0d,$20,$81
@ref203:
	.byte $20,$20,$21,$0d,$21,$21,$21,$0d,$21,$20,$20,$21,$0d,$21,$21,$21
	.byte $0d,$20,$81
	.byte $ff,$13
	.word @ref203
	.byte $ff,$13
	.word @ref203
@ref206:
	.byte $0e,$89,$0e,$89,$12,$8d,$09,$09,$08,$85,$04,$85
@ref207:
	.byte $0e,$89,$0e,$89,$16,$8d,$08,$85,$08,$85,$08,$85
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref208:
	.byte $bf
@ref209:
	.byte $bf
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@ref212:
	.byte $bf
@ref213:
	.byte $bf
@ref214:
	.byte $bf
@ref215:
	.byte $bf
@ref216:
	.byte $bf
@ref217:
	.byte $bf
@ref218:
	.byte $bf
@ref219:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$06
@song5ch0loop:
@ref220:
	.byte $bf
@ref221:
	.byte $bf
@ref222:
	.byte $84,$1b,$1b,$37,$1a,$32,$1a,$32,$1b,$33,$1b,$1b,$1b,$37,$1a,$32
	.byte $1a,$32,$1b,$33,$1a,$81
@ref223:
	.byte $1b,$1b,$37,$1a,$32,$1a,$32,$1b,$33,$1b,$1b,$1b,$37,$1a,$32,$1a
	.byte $32,$1b,$33,$1a,$81
	.byte $ff,$15
	.word @ref223
	.byte $ff,$15
	.word @ref223
@ref226:
	.byte $86,$1b,$32,$1a,$32,$1b,$33,$3d,$32,$3b,$33,$23,$2c,$22,$2c,$23
	.byte $29,$1b,$22,$25,$28,$81
@ref227:
	.byte $1b,$32,$1a,$32,$1b,$33,$3d,$32,$3b,$33,$23,$2c,$22,$2c,$23,$29
	.byte $1b,$22,$25,$28,$81
	.byte $ff,$15
	.word @ref227
	.byte $ff,$15
	.word @ref227
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref230:
	.byte $bf
@ref231:
	.byte $bf
@ref232:
	.byte $bf
@ref233:
	.byte $bf
@ref234:
	.byte $bf
@ref235:
	.byte $bf
@ref236:
	.byte $86,$33,$4a,$32,$4a,$33,$4b,$55,$4a,$53,$4b,$3b,$44,$3a,$44,$3b
	.byte $41,$33,$3a,$3d,$40,$81
@ref237:
	.byte $33,$4a,$32,$4a,$33,$4b,$55,$4a,$53,$4b,$3b,$44,$3a,$44,$3b,$41
	.byte $33,$3a,$3d,$40,$81
	.byte $ff,$15
	.word @ref237
	.byte $ff,$15
	.word @ref237
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref240:
	.byte $80,$1b,$1b,$37,$1a,$32,$1a,$32,$1b,$33,$1b,$1b,$1b,$37,$1a,$32
	.byte $1a,$32,$1b,$33,$1a,$81
	.byte $ff,$15
	.word @ref223
	.byte $ff,$15
	.word @ref223
	.byte $ff,$15
	.word @ref223
	.byte $ff,$15
	.word @ref223
	.byte $ff,$15
	.word @ref223
@ref246:
	.byte $33,$33,$41,$36,$37,$37,$32,$37,$33,$33,$33,$41,$36,$37,$37,$32
	.byte $37,$32,$81
	.byte $ff,$13
	.word @ref246
	.byte $ff,$13
	.word @ref246
	.byte $ff,$13
	.word @ref246
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref250:
	.byte $bf
@ref251:
	.byte $bf
@ref252:
	.byte $bf
@ref253:
	.byte $9f,$88,$02,$85,$08,$85,$02,$85,$08,$85
@ref254:
	.byte $10,$89,$11,$1e,$85,$1f,$1f,$10,$89,$11,$1e,$85,$1f,$1e,$81
@ref255:
	.byte $11,$11,$1b,$10,$1b,$11,$10,$1b,$11,$11,$11,$1b,$10,$1b,$11,$10
	.byte $1b,$10,$81
	.byte $ff,$0f
	.word @ref254
	.byte $ff,$13
	.word @ref255
	.byte $ff,$0f
	.word @ref254
	.byte $ff,$13
	.word @ref255
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref260:
	.byte $bf
@ref261:
	.byte $bf
@ref262:
	.byte $bf
@ref263:
	.byte $bf
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$07
@song6ch0loop:
@ref270:
	.byte $00,$bd
@ref271:
	.byte $00,$bd
@ref272:
	.byte $88,$32,$83,$40,$83,$33,$32,$83,$40,$83,$33,$32,$83,$40,$83,$33
	.byte $32,$83,$40,$83,$32,$81
@ref273:
	.byte $33,$32,$33,$3d,$32,$3d,$82,$3b,$3b,$37,$88,$33,$32,$33,$3d,$32
	.byte $3d,$82,$37,$37,$3a,$81
@ref274:
	.byte $88,$33,$32,$33,$3d,$32,$3d,$82,$3b,$3b,$37,$88,$33,$32,$33,$3d
	.byte $32,$3d,$82,$37,$37,$3a,$81
	.byte $ff,$13
	.word @ref274
@ref276:
	.byte $00,$bd
@ref277:
	.byte $00,$bd
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref278:
	.byte $bf
@ref279:
	.byte $bf
@ref280:
	.byte $bf
@ref281:
	.byte $bf
@ref282:
	.byte $88,$4b,$59,$4a,$59,$4b,$4a,$55,$4b,$59,$4b,$59,$5c,$53,$59,$5c
	.byte $55,$53,$58,$81
@ref283:
	.byte $4a,$58,$59,$4a,$59,$4b,$4a,$55,$4b,$59,$4b,$59,$5c,$53,$58,$52
	.byte $5c,$55,$53,$58,$81
	.byte $ff,$15
	.word @ref283
	.byte $ff,$15
	.word @ref283
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref286:
	.byte $bf
@ref287:
	.byte $bf
@ref288:
	.byte $bf
@ref289:
	.byte $bf
@ref290:
	.byte $bf
@ref291:
	.byte $bf
@ref292:
	.byte $bf
@ref293:
	.byte $bf
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref294:
	.byte $88,$1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b,$88
	.byte $1e,$00,$1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b
	.byte $88,$1e,$00
@ref295:
	.byte $1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b,$88,$1e
	.byte $1e,$1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b,$88
	.byte $1e,$00
@ref296:
	.byte $1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b,$88,$1e
	.byte $00,$1e,$00,$1e,$00,$80,$0b,$82,$20,$20,$00,$21,$20,$80,$0b,$88
	.byte $1e,$00
	.byte $ff,$1a
	.word @ref295
	.byte $ff,$1a
	.word @ref296
	.byte $ff,$1a
	.word @ref295
	.byte $ff,$1a
	.word @ref295
	.byte $ff,$1a
	.word @ref295
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref302:
	.byte $bf
@ref303:
	.byte $bf
@ref304:
	.byte $bf
@ref305:
	.byte $bf
@ref306:
	.byte $bf
@ref307:
	.byte $bf
@ref308:
	.byte $bf
@ref309:
	.byte $bf
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$04
@ref310:
	.byte $8a,$3f,$4d,$57,$4d,$57,$4f,$3f,$4d,$57,$4d,$57,$4f,$45,$43,$3a
	.byte $85
@ref311:
	.byte $3e,$85,$57,$4d,$57,$4f,$3e,$85,$57,$4d,$57,$4f,$44,$85,$4d,$52
	.byte $81
@ref312:
	.byte $3f,$4d,$57,$4d,$57,$4f,$3f,$4d,$57,$4d,$57,$4f,$45,$43,$3a,$85
	.byte $ff,$11
	.word @ref311
@song7ch0loop:
@ref314:
	.byte $bf
@ref315:
	.byte $bf
@ref316:
	.byte $8a,$3e,$85,$56,$85,$56,$85,$3e,$85,$56,$85,$56,$85,$44,$85,$3a
	.byte $85
@ref317:
	.byte $3e,$85,$56,$85,$56,$85,$3e,$85,$56,$85,$56,$85,$44,$85,$4c,$85
	.byte $ff,$10
	.word @ref312
	.byte $ff,$11
	.word @ref311
@ref320:
	.byte $3e,$85,$56,$85,$56,$85,$3e,$85,$56,$85,$56,$85,$44,$85,$3a,$85
	.byte $ff,$10
	.word @ref317
@ref322:
	.byte $bf
@ref323:
	.byte $bf
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@ref324:
	.byte $bf
@ref325:
	.byte $bf
@ref326:
	.byte $bf
@ref327:
	.byte $a7,$86,$1c,$85,$1e,$85,$22,$85
@song7ch1loop:
@ref328:
	.byte $86,$1f,$25,$00,$85,$1f,$25,$00,$85,$25,$29,$01,$25,$29,$01,$14
	.byte $1a,$00,$81
@ref329:
	.byte $1f,$21,$2d,$28,$89,$22,$85,$1e,$85,$1b,$1e,$89,$1a,$85
@ref330:
	.byte $1f,$25,$00,$85,$1f,$25,$00,$85,$25,$29,$01,$25,$29,$01,$14,$1a
	.byte $00,$81
	.byte $ff,$0e
	.word @ref329
	.byte $ff,$12
	.word @ref330
	.byte $ff,$0e
	.word @ref329
@ref334:
	.byte $1b,$24,$85,$1b,$22,$85,$1b,$1e,$a1
@ref335:
	.byte $1b,$24,$85,$1b,$24,$85,$1b,$1e,$a1
@ref336:
	.byte $00,$85,$24,$85,$00,$85,$1e,$85,$00,$85,$28,$85,$00,$85,$1e,$85
	.byte $ff,$10
	.word @ref336
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@ref338:
	.byte $bf
@ref339:
	.byte $bf
@ref340:
	.byte $bf
@ref341:
	.byte $bf
@song7ch2loop:
	.byte $ff,$12
	.word @ref328
	.byte $ff,$0e
	.word @ref329
	.byte $ff,$12
	.word @ref330
	.byte $ff,$0e
	.word @ref329
	.byte $ff,$12
	.word @ref330
	.byte $ff,$0e
	.word @ref329
	.byte $ff,$09
	.word @ref334
	.byte $ff,$09
	.word @ref335
	.byte $ff,$10
	.word @ref336
	.byte $ff,$10
	.word @ref336
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@ref352:
	.byte $00,$bd
@ref353:
	.byte $bf
@ref354:
	.byte $87,$82,$0a,$85,$88,$0e,$95,$82,$0a,$85,$88,$0e,$85,$82,$0e,$85
@ref355:
	.byte $87,$0a,$85,$88,$0e,$95,$82,$0a,$85,$88,$0e,$85,$82,$12,$85
@song7ch3loop:
	.byte $ff,$0b
	.word @ref354
	.byte $ff,$0b
	.word @ref355
@ref358:
	.byte $87,$0a,$85,$88,$0e,$95,$82,$0a,$85,$88,$0e,$85,$82,$0e,$85
	.byte $ff,$0b
	.word @ref355
	.byte $ff,$0b
	.word @ref358
	.byte $ff,$0b
	.word @ref355
	.byte $ff,$0b
	.word @ref358
	.byte $ff,$0b
	.word @ref355
	.byte $ff,$0b
	.word @ref358
	.byte $ff,$0b
	.word @ref355
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@ref366:
	.byte $bf
@ref367:
	.byte $bf
@ref368:
	.byte $bf
@ref369:
	.byte $bf
@song7ch4loop:
@ref370:
	.byte $bf
@ref371:
	.byte $bf
@ref372:
	.byte $bf
@ref373:
	.byte $bf
@ref374:
	.byte $bf
@ref375:
	.byte $bf
@ref376:
	.byte $bf
@ref377:
	.byte $bf
@ref378:
	.byte $bf
@ref379:
	.byte $bf
	.byte $fd
	.word @song7ch4loop


@song8ch0:
	.byte $fb,$06
@song8ch0loop:
@ref380:
	.byte $86,$32,$85,$33,$37,$3c,$3a,$3d,$3b,$37,$44,$85,$40,$85,$3d,$37
	.byte $37,$32,$81
@ref381:
	.byte $80,$3a,$36,$33,$40,$45,$40,$49,$48,$48,$40,$36,$83,$86,$40,$4a
	.byte $48,$48,$44,$44,$3c,$3a,$36,$85,$44,$85
@ref382:
	.byte $32,$85,$33,$37,$3c,$3a,$3d,$3b,$37,$44,$85,$40,$85,$3d,$37,$37
	.byte $32,$81
	.byte $ff,$18
	.word @ref381
@ref384:
	.byte $3c,$3a,$3d,$3b,$37,$44,$85,$3a,$85,$3c,$3a,$3d,$3b,$37,$32,$85
	.byte $36,$85
@ref385:
	.byte $3c,$3a,$3d,$3b,$37,$44,$85,$3a,$85,$40,$3a,$37,$3b,$37,$32,$85
	.byte $36,$85
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@song8ch1loop:
@ref386:
	.byte $bf
@ref387:
	.byte $bf
@ref388:
	.byte $bf
@ref389:
	.byte $bf
@ref390:
	.byte $bf
@ref391:
	.byte $bf
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@song8ch2loop:
@ref392:
	.byte $bf
@ref393:
	.byte $bf
@ref394:
	.byte $bf
@ref395:
	.byte $bf
@ref396:
	.byte $bf
@ref397:
	.byte $bf
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@song8ch3loop:
@ref398:
	.byte $82,$20,$20,$20,$04,$0f,$05,$20,$20,$20,$04,$0f,$0b,$20,$20,$21
	.byte $0f,$0b,$07,$13,$15,$0a,$81
@ref399:
	.byte $20,$20,$20,$04,$0f,$05,$20,$20,$20,$04,$0f,$0b,$20,$20,$21,$0f
	.byte $0b,$07,$13,$15,$0a,$81
	.byte $ff,$16
	.word @ref399
	.byte $ff,$16
	.word @ref399
	.byte $ff,$16
	.word @ref399
	.byte $ff,$16
	.word @ref399
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@song8ch4loop:
@ref404:
	.byte $bf
@ref405:
	.byte $bf
@ref406:
	.byte $bf
@ref407:
	.byte $bf
@ref408:
	.byte $bf
@ref409:
	.byte $bf
	.byte $fd
	.word @song8ch4loop


@song9ch0:
	.byte $fb,$05
@song9ch0loop:
@ref410:
	.byte $80,$44,$85,$44,$85,$2d,$44,$85,$45,$44,$85,$44,$83,$44,$2d,$44
	.byte $89
@ref411:
	.byte $40,$85,$40,$85,$29,$40,$85,$41,$40,$85,$40,$83,$40,$29,$40,$89
@ref412:
	.byte $44,$85,$44,$85,$2d,$44,$85,$45,$44,$85,$44,$83,$44,$2d,$44,$89
	.byte $ff,$10
	.word @ref411
	.byte $ff,$10
	.word @ref412
	.byte $ff,$10
	.word @ref411
	.byte $ff,$10
	.word @ref412
	.byte $ff,$10
	.word @ref411
	.byte $ff,$10
	.word @ref412
	.byte $ff,$10
	.word @ref411
	.byte $fd
	.word @song9ch0loop

@song9ch1:
@song9ch1loop:
@ref420:
	.byte $bf
@ref421:
	.byte $bf
@ref422:
	.byte $86,$33,$33,$4a,$85,$00,$85,$33,$33,$55,$58,$89,$52,$85,$32,$85
@ref423:
	.byte $4b,$4f,$59,$41,$53,$4f,$4b,$4e,$85,$4b,$4b,$4b,$4e,$85,$54,$85
@ref424:
	.byte $33,$33,$4a,$85,$00,$85,$33,$33,$55,$58,$89,$52,$85,$32,$85
@ref425:
	.byte $44,$85,$37,$40,$85,$37,$3a,$85,$33,$37,$3b,$3d,$40,$85,$36,$85
	.byte $ff,$0f
	.word @ref424
	.byte $ff,$10
	.word @ref423
	.byte $ff,$0f
	.word @ref424
	.byte $ff,$10
	.word @ref425
	.byte $fd
	.word @song9ch1loop

@song9ch2:
@song9ch2loop:
@ref430:
	.byte $bf
@ref431:
	.byte $bf
@ref432:
	.byte $bf
@ref433:
	.byte $bf
@ref434:
	.byte $bf
@ref435:
	.byte $bf
@ref436:
	.byte $80,$4a,$85,$4a,$5c,$61,$62,$85,$5c,$85,$4f,$5d,$63,$4f,$4a,$85
	.byte $54,$85
@ref437:
	.byte $4a,$85,$52,$54,$59,$60,$85,$5c,$85,$5d,$59,$55,$59,$5c,$85,$54
	.byte $85
@ref438:
	.byte $4a,$85,$4a,$5c,$61,$62,$85,$5c,$85,$4f,$5d,$63,$4f,$4a,$85,$54
	.byte $85
	.byte $ff,$11
	.word @ref437
	.byte $fd
	.word @song9ch2loop

@song9ch3:
@song9ch3loop:
@ref440:
	.byte $88,$21,$21,$20,$85,$0a,$85,$20,$20,$21,$20,$85,$20,$85,$0a,$85
	.byte $21,$20,$81
@ref441:
	.byte $21,$21,$20,$85,$0a,$85,$20,$20,$21,$20,$85,$20,$85,$0a,$85,$21
	.byte $20,$81
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $ff,$12
	.word @ref441
	.byte $fd
	.word @song9ch3loop

@song9ch4:
@song9ch4loop:
@ref450:
	.byte $bf
@ref451:
	.byte $bf
@ref452:
	.byte $bf
@ref453:
	.byte $bf
@ref454:
	.byte $bf
@ref455:
	.byte $bf
@ref456:
	.byte $bf
@ref457:
	.byte $bf
@ref458:
	.byte $bf
@ref459:
	.byte $bf
	.byte $fd
	.word @song9ch4loop


@song10ch0:
	.byte $fb,$04
@song10ch0loop:
@ref460:
	.byte $84,$1a,$83,$28,$85,$2d,$22,$83,$29,$32,$e1
	.byte $fd
	.word @song10ch0loop

@song10ch1:
@song10ch1loop:
@ref461:
	.byte $f9,$85
	.byte $fd
	.word @song10ch1loop

@song10ch2:
@song10ch2loop:
@ref462:
	.byte $f9,$85
	.byte $fd
	.word @song10ch2loop

@song10ch3:
@song10ch3loop:
@ref463:
	.byte $88,$08,$83,$20,$85,$09,$08,$83,$21,$20,$83,$20,$85,$08,$85,$82
	.byte $10,$85,$00,$c3
	.byte $fd
	.word @song10ch3loop

@song10ch4:
@song10ch4loop:
@ref464:
	.byte $f9,$85
	.byte $fd
	.word @song10ch4loop


@song11ch0:
	.byte $fb,$04
@song11ch0loop:
@ref465:
	.byte $96,$32,$9d,$32,$85,$36,$95
@ref466:
	.byte $3a,$85,$36,$85,$3a,$85,$36,$85,$3c,$85,$3a,$85,$36,$85,$32,$85
@ref467:
	.byte $32,$89,$3c,$89,$3a,$8d,$32,$85,$28,$85,$30,$85
	.byte $ff,$0c
	.word @ref467
@ref469:
	.byte $32,$89,$3c,$89,$3a,$a5
@ref470:
	.byte $32,$89,$3c,$89,$40,$a5
@ref471:
	.byte $33,$32,$85,$3c,$89,$3a,$85,$36,$85,$32,$85,$28,$85,$30,$85
@ref472:
	.byte $33,$32,$85,$3c,$89,$3a,$85,$3c,$85,$3a,$85,$32,$85,$36,$85
@ref473:
	.byte $84,$22,$85,$25,$01,$29,$22,$85,$30,$85,$24,$89,$2c,$85,$33,$00
	.byte $81
@ref474:
	.byte $30,$85,$22,$85,$36,$85,$28,$85,$40,$8d,$3a,$89,$00,$81
@ref475:
	.byte $22,$85,$25,$01,$29,$22,$85,$30,$85,$24,$89,$2c,$85,$33,$00,$81
	.byte $ff,$0e
	.word @ref474
	.byte $fd
	.word @song11ch0loop

@song11ch1:
@song11ch1loop:
@ref477:
	.byte $bf
@ref478:
	.byte $bf
@ref479:
	.byte $bf
@ref480:
	.byte $bf
@ref481:
	.byte $92,$1b,$24,$85,$24,$89,$1e,$85,$1a,$85,$1e,$85,$28,$85,$1e,$85
@ref482:
	.byte $1b,$24,$85,$24,$89,$1e,$85,$1a,$85,$1e,$85,$28,$85,$1e,$85
	.byte $ff,$0f
	.word @ref482
	.byte $ff,$0f
	.word @ref482
@ref485:
	.byte $bf
@ref486:
	.byte $bf
@ref487:
	.byte $8a,$1a,$85,$92,$32,$85,$8a,$1a,$85,$92,$32,$85,$8a,$1a,$85,$92
	.byte $32,$85,$8a,$1a,$85,$92,$32,$85
@ref488:
	.byte $8a,$1e,$85,$92,$36,$85,$8a,$1e,$85,$92,$36,$85,$8a,$1e,$85,$92
	.byte $36,$85,$8a,$1e,$85,$92,$36,$85
	.byte $fd
	.word @song11ch1loop

@song11ch2:
@song11ch2loop:
@ref489:
	.byte $86,$1a,$89,$01,$24,$89,$01,$1a,$89,$01,$24,$89,$00,$81
@ref490:
	.byte $1e,$89,$01,$28,$89,$01,$1e,$89,$01,$28,$89,$00,$81
@ref491:
	.byte $1a,$89,$01,$28,$89,$01,$1a,$89,$01,$28,$89,$00,$81
@ref492:
	.byte $1e,$89,$01,$24,$89,$01,$1e,$89,$01,$24,$89,$00,$81
@ref493:
	.byte $1a,$89,$01,$24,$89,$01,$1a,$89,$01,$24,$89,$00,$81
	.byte $ff,$0d
	.word @ref490
	.byte $ff,$0d
	.word @ref491
	.byte $ff,$0d
	.word @ref492
	.byte $ff,$0d
	.word @ref493
	.byte $ff,$0d
	.word @ref490
	.byte $ff,$0d
	.word @ref491
	.byte $ff,$0d
	.word @ref492
	.byte $fd
	.word @song11ch2loop

@song11ch3:
@song11ch3loop:
@ref501:
	.byte $90,$19,$19,$19,$19,$8e,$05,$90,$19,$19,$19,$19,$19,$19,$19,$8e
	.byte $05,$90,$19,$19,$18,$81
@ref502:
	.byte $19,$19,$19,$19,$8e,$05,$90,$19,$19,$19,$19,$19,$19,$19,$8e,$05
	.byte $90,$19,$19,$18,$81
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $ff,$11
	.word @ref502
	.byte $fd
	.word @song11ch3loop

@song11ch4:
@song11ch4loop:
@ref513:
	.byte $bf
@ref514:
	.byte $bf
@ref515:
	.byte $bf
@ref516:
	.byte $bf
@ref517:
	.byte $bf
@ref518:
	.byte $bf
@ref519:
	.byte $bf
@ref520:
	.byte $bf
@ref521:
	.byte $bf
@ref522:
	.byte $bf
@ref523:
	.byte $bf
@ref524:
	.byte $bf
	.byte $fd
	.word @song11ch4loop


@song12ch0:
	.byte $fb,$06
@song12ch0loop:
@ref525:
	.byte $96,$33,$41,$3a,$85,$33,$3d,$36,$85,$33,$3b,$32,$85,$33,$37,$3b
	.byte $3d,$33,$41,$32,$85,$41,$3a,$89,$44,$85,$41,$3d,$3b,$37,$44,$85
@ref526:
	.byte $f9,$85
@ref527:
	.byte $33,$41,$3a,$85,$33,$3d,$36,$85,$33,$3b,$32,$85,$33,$37,$3b,$3d
	.byte $33,$41,$32,$85,$41,$3a,$89,$44,$85,$41,$3d,$3b,$37,$44,$85
@ref528:
	.byte $f9,$85
@ref529:
	.byte $32,$85,$3a,$85,$40,$85,$44,$85,$3c,$85,$36,$85,$32,$85,$41,$3d
	.byte $3a,$85,$3b,$3d,$3a,$85,$33,$37,$3a,$85,$3c,$85,$3a,$8d
@ref530:
	.byte $32,$85,$40,$85,$48,$85,$4a,$85,$48,$85,$44,$85,$40,$85,$4f,$4b
	.byte $48,$85,$49,$45,$40,$85,$33,$37,$3a,$85,$3c,$85,$3a,$8d
	.byte $fd
	.word @song12ch0loop

@song12ch1:
@song12ch1loop:
@ref531:
	.byte $94,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b
	.byte $3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b
	.byte $3c,$81
@ref532:
	.byte $33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d
	.byte $33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3d,$33,$37,$3b,$3c
	.byte $81
	.byte $ff,$21
	.word @ref532
	.byte $ff,$21
	.word @ref532
	.byte $ff,$21
	.word @ref532
	.byte $ff,$21
	.word @ref532
	.byte $fd
	.word @song12ch1loop

@song12ch2:
@song12ch2loop:
@ref537:
	.byte $86,$32,$9d,$3c,$9d,$44,$9d,$40,$9d
@ref538:
	.byte $32,$9d,$3c,$9d,$44,$9d,$40,$9d
	.byte $ff,$08
	.word @ref538
	.byte $ff,$08
	.word @ref538
	.byte $ff,$08
	.word @ref538
	.byte $ff,$08
	.word @ref538
	.byte $fd
	.word @song12ch2loop

@song12ch3:
@song12ch3loop:
@ref543:
	.byte $8e,$14,$85,$90,$19,$8e,$15,$14,$85,$90,$18,$85,$8e,$14,$85,$90
	.byte $19,$8e,$15,$14,$85,$90,$18,$85,$8e,$14,$85,$90,$19,$8e,$15,$14
	.byte $85,$90,$18,$85,$8e,$14,$85,$90,$19,$8e,$15,$14,$85,$90,$18,$85
	.byte $ff,$20
	.word @ref543
	.byte $ff,$20
	.word @ref543
	.byte $ff,$20
	.word @ref543
	.byte $ff,$20
	.word @ref543
	.byte $ff,$20
	.word @ref543
	.byte $fd
	.word @song12ch3loop

@song12ch4:
@song12ch4loop:
@ref549:
	.byte $f9,$85
@ref550:
	.byte $f9,$85
@ref551:
	.byte $f9,$85
@ref552:
	.byte $f9,$85
@ref553:
	.byte $f9,$85
@ref554:
	.byte $f9,$85
	.byte $fd
	.word @song12ch4loop


@song13ch0:
	.byte $fb,$04
@song13ch0loop:
@ref555:
	.byte $00,$bd
@ref556:
	.byte $bf
@ref557:
	.byte $86,$32,$00,$32,$00,$32,$00,$83,$36,$00,$83,$40,$00,$83,$37,$3a
	.byte $85,$3c,$89,$45,$00,$81
@ref558:
	.byte $bf
@ref559:
	.byte $32,$00,$32,$00,$32,$00,$83,$36,$00,$83,$40,$00,$83,$37,$3a,$85
	.byte $3c,$89,$37,$00,$81
@ref560:
	.byte $87,$45,$01,$33,$37,$3d,$41,$37,$01,$33,$3d,$36,$85,$32,$85
@ref561:
	.byte $00,$bd
@ref562:
	.byte $bf
	.byte $fd
	.word @song13ch0loop

@song13ch1:
@song13ch1loop:
@ref563:
	.byte $86,$36,$00,$36,$00,$83,$44,$00,$3a,$00,$83,$3a,$00,$40,$00,$83
	.byte $3c,$00,$3c,$00,$40,$00,$3c,$00,$83,$3a,$00,$36,$00
@ref564:
	.byte $36,$00,$83,$36,$00,$40,$00,$3c,$00,$83,$3c,$00,$36,$00,$83,$40
	.byte $00,$3c,$00,$3a,$00,$44,$00,$83,$3c,$00,$3a,$00
@ref565:
	.byte $36,$00,$36,$00,$83,$44,$00,$3a,$00,$83,$3a,$00,$40,$00,$83,$3c
	.byte $00,$3c,$00,$40,$00,$3c,$00,$83,$3a,$00,$36,$00
	.byte $ff,$1c
	.word @ref564
@ref567:
	.byte $36,$00,$36,$00,$36,$00,$44,$00,$3a,$00,$3a,$00,$3a,$00,$40,$00
	.byte $3c,$00,$3c,$00,$3c,$00,$40,$00,$3c,$00,$3c,$00,$3a,$00,$36,$00
@ref568:
	.byte $36,$00,$36,$00,$36,$00,$40,$00,$3c,$00,$3c,$00,$3c,$00,$36,$00
	.byte $40,$00,$40,$00,$3c,$00,$3a,$00,$44,$00,$40,$00,$3c,$00,$3a,$00
	.byte $ff,$1c
	.word @ref565
	.byte $ff,$1c
	.word @ref564
	.byte $fd
	.word @song13ch1loop

@song13ch2:
@song13ch2loop:
@ref571:
	.byte $8c,$32,$85,$4a,$00,$4a,$00,$4a,$85,$32,$00,$32,$85,$4a,$00,$4a
	.byte $00,$4a,$00,$4a,$85,$32,$00,$32,$00
@ref572:
	.byte $32,$85,$4a,$00,$4a,$00,$4a,$85,$32,$00,$32,$85,$4a,$00,$4a,$00
	.byte $4a,$00,$4a,$85,$32,$00,$32,$00
	.byte $ff,$18
	.word @ref572
	.byte $ff,$18
	.word @ref572
	.byte $ff,$18
	.word @ref572
	.byte $ff,$18
	.word @ref572
	.byte $ff,$18
	.word @ref572
	.byte $ff,$18
	.word @ref572
	.byte $fd
	.word @song13ch2loop

@song13ch3:
@song13ch3loop:
@ref579:
	.byte $98,$08,$85,$9a,$09,$09,$10,$85,$0b,$08,$85,$09,$09,$09,$0e,$85
	.byte $09,$08,$81
@ref580:
	.byte $98,$06,$85,$9a,$0b,$0b,$12,$85,$0b,$0a,$85,$0b,$0b,$0b,$12,$85
	.byte $0b,$0a,$81
	.byte $ff,$11
	.word @ref579
	.byte $ff,$11
	.word @ref580
	.byte $ff,$11
	.word @ref579
	.byte $ff,$11
	.word @ref580
@ref585:
	.byte $00,$bd
@ref586:
	.byte $bf
	.byte $fd
	.word @song13ch3loop

@song13ch4:
@song13ch4loop:
@ref587:
	.byte $bf
@ref588:
	.byte $bf
@ref589:
	.byte $bf
@ref590:
	.byte $bf
@ref591:
	.byte $bf
@ref592:
	.byte $bf
@ref593:
	.byte $bf
@ref594:
	.byte $bf
	.byte $fd
	.word @song13ch4loop


@song14ch0:
	.byte $fb,$04
@song14ch0loop:
@ref595:
	.byte $8c,$33,$37,$3b,$33,$33,$3d,$3d,$32,$85,$41,$37,$3b,$41,$3d,$3b
	.byte $36,$81
@ref596:
	.byte $33,$37,$3b,$33,$33,$3d,$3d,$32,$85,$41,$45,$3b,$41,$3d,$3b,$36
	.byte $81
@ref597:
	.byte $33,$37,$3b,$33,$33,$3d,$3d,$32,$85,$41,$37,$3b,$41,$3d,$3b,$36
	.byte $81
	.byte $ff,$11
	.word @ref596
	.byte $ff,$11
	.word @ref597
	.byte $ff,$11
	.word @ref596
	.byte $ff,$11
	.word @ref597
@ref602:
	.byte $33,$37,$3b,$33,$33,$3d,$3d,$32,$85,$3b,$37,$3b,$41,$3d,$3b,$36
	.byte $81
@ref603:
	.byte $32,$85,$32,$85,$32,$85,$32,$85,$32,$9d
	.byte $ff,$0a
	.word @ref603
	.byte $ff,$0a
	.word @ref603
	.byte $ff,$0a
	.word @ref603
	.byte $fd
	.word @song14ch0loop

@song14ch1:
@song14ch1loop:
@ref607:
	.byte $00,$bd
@ref608:
	.byte $bf
@ref609:
	.byte $8c,$3b,$37,$33,$37,$37,$33,$3d,$3d,$41,$37,$3a,$85,$33,$3d,$33
	.byte $3c,$81
@ref610:
	.byte $3b,$37,$33,$37,$37,$33,$41,$3d,$41,$37,$3a,$85,$33,$3d,$33,$3c
	.byte $81
@ref611:
	.byte $3b,$37,$33,$37,$37,$33,$3d,$3d,$41,$37,$3a,$85,$33,$3d,$33,$3c
	.byte $81
	.byte $ff,$11
	.word @ref610
	.byte $ff,$11
	.word @ref611
	.byte $ff,$11
	.word @ref610
@ref615:
	.byte $36,$85,$3a,$85,$3c,$85,$41,$41,$41,$33,$3d,$33,$3b,$33,$37,$32
	.byte $81
	.byte $ff,$11
	.word @ref615
	.byte $ff,$11
	.word @ref615
	.byte $ff,$11
	.word @ref615
	.byte $fd
	.word @song14ch1loop

@song14ch2:
@song14ch2loop:
@ref619:
	.byte $00,$bd
@ref620:
	.byte $bf
@ref621:
	.byte $84,$40,$8d,$32,$8d,$3c,$8d,$36,$8d
@ref622:
	.byte $40,$8d,$32,$8d,$44,$85,$40,$85,$3c,$85,$3a,$85
@ref623:
	.byte $00,$bd
@ref624:
	.byte $bf
@ref625:
	.byte $00,$bd
@ref626:
	.byte $bf
@ref627:
	.byte $40,$8d,$32,$8d,$3c,$8d,$36,$8d
	.byte $ff,$0c
	.word @ref622
	.byte $ff,$08
	.word @ref627
	.byte $ff,$0c
	.word @ref622
	.byte $fd
	.word @song14ch2loop

@song14ch3:
@song14ch3loop:
@ref631:
	.byte $00,$bd
@ref632:
	.byte $bf
@ref633:
	.byte $8e,$14,$8d,$14,$8d,$14,$8d,$14,$8d
@ref634:
	.byte $14,$8d,$14,$8d,$14,$8d,$14,$8d
@ref635:
	.byte $14,$85,$04,$85,$14,$85,$04,$85,$14,$85,$04,$85,$14,$85,$04,$85
	.byte $ff,$10
	.word @ref635
	.byte $ff,$10
	.word @ref635
	.byte $ff,$10
	.word @ref635
@ref639:
	.byte $14,$bd
@ref640:
	.byte $14,$bd
@ref641:
	.byte $14,$bd
@ref642:
	.byte $14,$bd
	.byte $fd
	.word @song14ch3loop

@song14ch4:
@song14ch4loop:
@ref643:
	.byte $bf
@ref644:
	.byte $bf
@ref645:
	.byte $bf
@ref646:
	.byte $bf
@ref647:
	.byte $bf
@ref648:
	.byte $bf
@ref649:
	.byte $bf
@ref650:
	.byte $bf
@ref651:
	.byte $bf
@ref652:
	.byte $bf
@ref653:
	.byte $bf
@ref654:
	.byte $bf
	.byte $fd
	.word @song14ch4loop


@song15ch0:
@song15ch0loop:
@ref655:
	.byte $86,$2c,$85,$1e,$85,$2c,$85,$1e,$85,$2d,$1f,$29,$1f,$29,$2d,$37
	.byte $33,$3c,$85,$36,$85,$40,$85,$3c,$85,$3a,$85,$32,$85,$33,$33,$36
	.byte $85
@ref656:
	.byte $2c,$85,$1e,$85,$2c,$85,$1e,$85,$2d,$1f,$29,$1f,$29,$2d,$37,$33
	.byte $3c,$85,$36,$85,$44,$85,$3a,$85,$4a,$85,$48,$85,$32,$85,$36,$85
@ref657:
	.byte $2c,$85,$1e,$85,$2c,$85,$1e,$85,$2d,$1f,$29,$1f,$29,$2d,$37,$33
	.byte $3c,$85,$36,$85,$40,$85,$3c,$85,$3a,$85,$32,$85,$33,$33,$36,$85
	.byte $ff,$20
	.word @ref656
	.byte $ff,$20
	.word @ref657
	.byte $ff,$20
	.word @ref656
	.byte $ff,$20
	.word @ref657
	.byte $ff,$20
	.word @ref656
	.byte $ff,$20
	.word @ref657
	.byte $ff,$20
	.word @ref656
	.byte $fd
	.word @song15ch0loop

@song15ch1:
	.byte $fb,$06
@song15ch1loop:
@ref665:
	.byte $fb,$03,$f9,$85
@ref666:
	.byte $f9,$85
@ref667:
	.byte $f9,$85
@ref668:
	.byte $f9,$85
@ref669:
	.byte $fb,$06,$f9,$85
@ref670:
	.byte $f9,$85
@ref671:
	.byte $f9,$85
@ref672:
	.byte $f9,$85
@ref673:
	.byte $fb,$05,$f9,$85
@ref674:
	.byte $f9,$85
	.byte $fd
	.word @song15ch1loop

@song15ch2:
@song15ch2loop:
@ref675:
	.byte $00,$f9,$83
@ref676:
	.byte $00,$f9,$83
@ref677:
	.byte $86,$33,$3c,$89,$33,$3c,$89,$33,$3c,$89,$33,$3c,$89,$33,$40,$89
	.byte $33,$40,$89,$33,$40,$89,$33,$40,$89
@ref678:
	.byte $33,$3c,$89,$33,$3c,$89,$33,$3c,$89,$33,$3c,$89,$33,$40,$89,$33
	.byte $40,$89,$33,$40,$89,$33,$40,$89
	.byte $ff,$18
	.word @ref678
	.byte $ff,$18
	.word @ref678
	.byte $ff,$18
	.word @ref678
	.byte $ff,$18
	.word @ref678
@ref683:
	.byte $00,$f9,$83
@ref684:
	.byte $00,$f9,$83
	.byte $fd
	.word @song15ch2loop

@song15ch3:
@song15ch3loop:
@ref685:
	.byte $96,$09,$13,$13,$09,$13,$13,$09,$09,$13,$13,$09,$13,$09,$09,$09
	.byte $09,$13,$09,$17,$13,$13,$11,$0d,$07,$07,$0d,$09,$06,$91
@ref686:
	.byte $09,$13,$13,$09,$13,$13,$09,$09,$13,$13,$09,$13,$09,$09,$09,$09
	.byte $13,$09,$17,$13,$13,$11,$0d,$07,$07,$0d,$09,$06,$91
@ref687:
	.byte $f9,$85
@ref688:
	.byte $f9,$85
	.byte $ff,$1d
	.word @ref686
	.byte $ff,$1d
	.word @ref686
@ref691:
	.byte $f9,$85
@ref692:
	.byte $f9,$85
@ref693:
	.byte $f9,$85
@ref694:
	.byte $f9,$85
	.byte $fd
	.word @song15ch3loop

@song15ch4:
@song15ch4loop:
@ref695:
	.byte $f9,$85
@ref696:
	.byte $f9,$85
@ref697:
	.byte $f9,$85
@ref698:
	.byte $f9,$85
@ref699:
	.byte $f9,$85
@ref700:
	.byte $f9,$85
@ref701:
	.byte $f9,$85
@ref702:
	.byte $f9,$85
@ref703:
	.byte $f9,$85
@ref704:
	.byte $f9,$85
	.byte $fd
	.word @song15ch4loop
